@base_address = https://localhost:8443
@admin_auth = "Basic admin admin"

###
GET {{base_address}}/api/tlsmanager/importedcertificates
Accept: application/json
X-Requested-With: IntelliJ
Authorization: {{admin_auth}}


###
GET {{base_address}}/api/tlsmanager/keystore
Accept: application/octet-stream
X-Requested-With: IntelliJ
Authorization: {{admin_auth}}

>> {{$historyFolder}}/keystore.p12

###

POST {{base_address}}/api/tlsmanager/keystore
Content-Type: application/octet-stream
X-Requested-With: IntelliJ
X-Keystore-Password: yohoo
Authorization: {{admin_auth}}

< .sdkmanrc



