@base_address = https://localhost:8443
@username = admin
@password = admin

###
GET {{base_address}}/api/tlsmanager/importedcertificates
Accept: application/json
X-Requested-With: IntelliJ
Authorization: Basic {{username}} {{password}}

###
GET {{base_address}}/api/tlsmanager/keystore
Accept: application/octet-stream
X-Requested-With: IntelliJ
Authorization: Basic {{username}} {{password}}

>> {{$historyFolder}}/keystore.p12

###

POST {{base_address}}/api/tlsmanager/keystore
Content-Type: application/octet-stream
X-Requested-With: IntelliJ
X-Keystore-Password: yohoo
Authorization: Basic {{username}} {{password}}

< .sdkmanrc



